- name: install opensmtpd related packages
  apt:
    name:
      - opensmtpd
      - mailutils

- name: create config directories
  file:
    state: directory
    name: "/etc/smtpd/{{ mailrelay_opensmtpd_config_directory_item }}"
    owner: opensmtpd
    group: opensmtpd
    mode: 0700
  with_items:
    - filters
    - tables
  loop_control:
    loop_var: mailrelay_opensmtpd_config_directory_item

- name: template /etc/smtpd.conf
  template:
    src: templates/etc/smtpd.conf.j2
    dest: /etc/smtpd.conf
    owner: opensmtpd
    group: opensmtpd
    mode: 0600
  notify: restart opensmtpd

- name: template /etc/smtpd/tables/relay_secrets
  template:
    src: templates/etc/smtpd/tables/relay_secrets.j2
    dest: /etc/smtpd/tables/relay_secrets
    owner: opensmtpd
    group: opensmtpd
    mode: 0600
  notify: restart opensmtpd

- name: template /etc/mailname
  template:
    src: "templates/etc/mailname.j2"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart opensmtpd
