- name: Converge
  hosts: all
  roles:
    - role: role-mailrelay-opensmtpd
  vars:

    # Encryption passphrase for the mail queue files
    # Generate via:
    # openssl rand -hex 16
    # This should be in the password-store!
    mailrelay_opensmtpd_conf_queue_encryption: bab0dddf70fedbc8b2bd59af0abe308f

    # Hostname for this mailrelay - should not be the servers actual hostname
    # Commonly just the domain of the company running the server
    # Will be written into the header of all outgoing emails
    mailrelay_opensmtpd_mailname: mailout.example.com

    # List of relay information
    mailrelay_opensmtpd_relays:
        # Alias for this relay
      - alias: myrelay
        # Relay server DNS name or IP
        server: "mail.example.com"
        # Relay server protocol (Documentation: https://man.openbsd.org/smtpd.conf#host)
        protocol: "smtp+tls"
        # Enforce TLS (default: True)
        tls: False
        # Relay server port
        port: "587"
        # Relay server SMTP login
        login: opensmtpd@example.com
        # Relay server SMTP password
        # This should be in the password-store!
        password: veryveryveryveryveryverysecret
        # Linux of sender addresses to apply this relay for
        from:
          - root
          - www-data
          - opensmtpd@example.com

      - alias: backup
        server: "mail.beispiel.de"
        protocol: "smtps"
        tls: True
        port: "465"
        login: backup@beispiel.de
        password: superduperhyperextremelysecret
        from:
          - backuppc



    # Only for molecule
    # In playbooks this is in inventory/group_vars/all.yml by default
    internal_private_domain: exa.io
    customer_main_domain: example.com
